#!/usr/bin/env python3
"""Generate the model and pricing tables from a captured GET /v1/manifold/models response.

Input:  data/models.json  (the response body, saved verbatim)
Output: snippets/*.mdx    (Mintlify snippets, imported by the pages that show the tables)

Every number on the model and pricing pages comes from here, so the published tables
cannot drift from the catalog they were captured from.

The weekly Catalog refresh workflow captures the catalog and runs this, opening a pull
request when anything moved. To do the same locally:

    TRISTACK_API_KEY=... python tools/fetch_catalog.py
    python tools/generate_pricing.py
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "models.json"
SNIPPETS = ROOT / "snippets"

# How the catalog is grouped into families on the page, in the order the sections appear.
# Keyed on alias, never on the display name: the catalog names a model without any vendor
# prefix ("Nova Micro"), so a name carries nothing that can be relied on as a grouping key.
# Every alias in the catalog must appear here or the run fails.
FAMILIES: list[tuple[str, tuple[str, ...]]] = [
    ("Opus, Sonnet and Haiku", ("opus-4-6", "sonnet-4-6", "haiku-4-5")),
    ("Nova", ("nova-micro", "nova-lite", "nova-pro", "nova-2-lite")),
    ("DeepSeek", ("deepseek-v3-2", "deepseek-r1")),
    ("Gemma 3", ("gemma-3-4b", "gemma-3-12b", "gemma-3-27b")),
    ("Llama", ("llama-3-8b", "llama-3-70b", "llama-3-1-8b", "llama-3-1-70b", "llama-3-3-70b")),
    ("MiniMax", ("minimax-m2", "minimax-m2-1", "minimax-m2-5")),
    ("Devstral", ("devstral-2",)),
    ("Magistral", ("magistral-small",)),
    ("Mistral", ("mistral-7b", "mistral-large", "mistral-large-3", "mistral-small")),
    ("Pixtral", ("pixtral-large",)),
    ("Voxtral", ("voxtral-mini", "voxtral-small")),
    ("Ministral", ("ministral-3b", "ministral-8b", "ministral-14b")),
    ("Mixtral", ("mixtral-8x7b",)),
    ("Kimi", ("kimi-k2-thinking", "kimi-k2-5")),
    (
        "Nemotron",
        (
            "nemotron-nano-9b",
            "nemotron-nano-12b",
            "nemotron-nano-3-30b",
            "nemotron-super-120b",
        ),
    ),
    (
        "gpt-oss",
        ("gpt-oss-20b", "gpt-oss-120b", "gpt-oss-safeguard-20b", "gpt-oss-safeguard-120b"),
    ),
    (
        "Qwen3",
        ("qwen3-32b", "qwen3-coder-30b", "qwen3-coder-next", "qwen3-next-80b", "qwen3-vl-235b"),
    ),
    ("Palmyra", ("palmyra-vision-7b",)),
    ("GLM", ("glm-4-7", "glm-4-7-flash", "glm-5")),
]

# Aliases the catalog still lists but that cannot be served yet. Empty as of 2026-08-26:
# GET /v1/manifold/models returns only servable models, so a switched-off one does not reach
# a capture at all and there is nothing to warn about. Kept rather than deleted because the
# machinery is what a "listed but not yet callable" state would need again, and because an
# alias put back here is one line rather than a rewrite of three snippets.
PENDING_ALIASES: set[str] = set()

# Aliases that accept image content blocks. The catalog endpoint does not report this, so
# it is tracked here and asserted against the catalog on every run. Delete this list in
# favour of the API the day the catalog response carries a vision flag of its own.
VISION_ALIASES = {
    "opus-4-6",
    "sonnet-4-6",
    "haiku-4-5",
    "nova-lite",
    "nova-pro",
    "nova-2-lite",
    "gemma-3-4b",
    "gemma-3-12b",
    "gemma-3-27b",
    "magistral-small",
    "ministral-3b",
    "ministral-8b",
    "ministral-14b",
    "mistral-large-3",
    "pixtral-large",
    "kimi-k2-5",
    "nemotron-nano-12b",
    "qwen3-vl-235b",
    "palmyra-vision-7b",
}

NOTICE = "Generated by tools/generate_pricing.py from data/models.json. Do not edit."


class Mintlify:
    """snippets/*.mdx, imported into a page with `import X from '/snippets/x.mdx'`.

    MDX is not markdown. An HTML comment is a parse error there, and `{` opens a JavaScript
    expression, so the banner is a JSX comment and everything the catalog supplies is put
    through mdx_safe() before it is written.
    """

    directory = SNIPPETS
    suffix = ".mdx"
    banner = f"{{/* {NOTICE} */}}"

    @staticmethod
    def warning(title: str, text: str) -> list[str]:
        # Mintlify's <Warning> takes no title, so the title leads the sentence instead.
        # Two-space indent, never four: four would read as an indented code block.
        return ["<Warning>", "", f"  **{title}.** {text}", "", "</Warning>", ""]


def targets() -> list[type[Mintlify]]:
    return [Mintlify]


# MDX reads `{` as the start of an expression and `<` as the start of a tag, so a display
# name carrying either would publish as a broken page rather than as a wrong number. The
# catalog is the only source of these strings, so they are checked once, here, on the way in.
MDX_HOSTILE = "{}<>"


def mdx_safe(models: list[dict]) -> None:
    for model in models:
        for field in ("alias", "displayName"):
            value = str(model[field])
            found = sorted({character for character in value if character in MDX_HOSTILE})
            if found:
                raise SystemExit(
                    f"{model['alias']}.{field} carries {found}, which MDX cannot render "
                    f"unescaped: {value!r}"
                )


def lossless(value: Decimal, rendered: str) -> str:
    """
    Guard against publishing a rounded price. A rate the catalog carries at a precision the
    renderer cannot reproduce would ship as a wrong number rather than a failed build, which
    is the one failure mode a price table must not have.
    """
    if Decimal(rendered) != value:
        raise SystemExit(f"Rate {value} does not survive rendering as {rendered!r}")
    return rendered


def paise(value: Decimal) -> str:
    return lossless(value, f"{value:.2f}")


def unit_paise(value: Decimal) -> str:
    """
    A per-unit embedding rate, which is genuinely sub-paise and needs the extra places.

    A chat rate is per 1000 tokens and lands in the tens or hundreds of paise, so two decimals
    hold it exactly. A per-request or per-image rate is the price of ONE thing: Marengo bills
    about 0.878 paise for a text request and 0.376 for the image increment. Rendered at two
    places those become 0.88 and 0.38, which lossless() correctly refuses, because publishing
    them would overstate the rate by roughly one percent forever. The fix is places, not
    rounding, so the trailing zeros are trimmed to keep whole-paise figures readable.
    """
    rendered = f"{value:.4f}".rstrip("0").rstrip(".")
    return lossless(value, rendered or "0")


def servable(models: list[dict]) -> list[dict]:
    return [model for model in models if model["alias"] not in PENDING_ALIASES]


def load() -> list[dict]:
    payload = json.loads(SOURCE.read_text(), parse_float=Decimal, parse_int=Decimal)
    return payload["models"]


def group(models: list[dict]) -> dict[str, list[dict]]:
    """
    Split the catalog into the families above, failing loudly rather than guessing: an
    alias nobody mapped would otherwise vanish from the page, and a pending alias that
    left the catalog would leave a warning standing over nothing.
    """
    mapped = [alias for _, aliases in FAMILIES for alias in aliases]
    duplicated = sorted({alias for alias in mapped if mapped.count(alias) > 1})
    if duplicated:
        raise SystemExit(f"Aliases listed in more than one family: {duplicated}")

    known = {model["alias"] for model in models}
    unmapped = sorted(known - set(mapped))
    if unmapped:
        raise SystemExit(f"Catalog aliases with no family in FAMILIES: {unmapped}")

    stale = sorted((set(mapped) | PENDING_ALIASES) - known)
    if stale:
        raise SystemExit(f"Aliases mapped here but missing from the catalog: {stale}")

    by_alias = {model["alias"]: model for model in models}
    return {
        heading: [by_alias[alias] for alias in aliases] for heading, aliases in FAMILIES
    }


def catalog_rows(models: list[dict]) -> list[str]:
    # Only the charged price is published. How a price is arrived at is not a column.
    header = [
        "| Alias | Model | Vision | Paise / 1K in | Paise / 1K out |",
        "|---|---|:--:|---:|---:|",
    ]
    rows = [
        "| `{alias}` | {name} | {vision} | {pi} | {po} |".format(
            alias=model["alias"],
            name=model["displayName"],
            vision="yes" if model["alias"] in VISION_ALIASES else "",
            pi=paise(model["paisePer1KTokensIn"]),
            po=paise(model["paisePer1KTokensOut"]),
        )
        for model in models
    ]
    return header + rows


def pending_admonition(target, aliases: list[str], closing: str) -> list[str]:
    """
    The "not servable yet" warning, emitted above the rows it covers so a reader scanning
    the table meets it before the prices. Generated from PENDING_ALIASES everywhere it
    appears: a hand-typed copy would outlive the entitlement it describes.

    The cause is deliberately left at "account-level access": nothing in the catalog
    response reports why an alias is unservable, so anything more specific would be invented.
    """
    if not aliases:
        return []
    named = ", ".join(f"`{alias}`" for alias in aliases)
    return target.warning(
        "Not servable yet",
        f"{named} are listed here but are switched off on this deployment, so "
        "`GET /v1/manifold/models` does not return them and a call answers "
        "`400 unknown_model`, the same answer a misspelt alias gets. It is refused before "
        f"any wallet hold is placed, so nothing is charged. {closing}",
    )


def write_catalog(target, families: dict[str, list[dict]]) -> None:
    lines = [target.banner, ""]
    for family, models in families.items():
        lines.append(f"### {family}")
        lines.append("")
        lines.extend(
            pending_admonition(
                target,
                [m["alias"] for m in models if m["alias"] in PENDING_ALIASES],
                "The prices below are what they will bill once that clears.",
            )
        )
        lines.extend(catalog_rows(models))
        lines.append("")
    (target.directory / f"model-catalog{target.suffix}").write_text("\n".join(lines))


def write_summary(target, models: list[dict], families: dict[str, list[dict]]) -> None:
    lines = [
        target.banner,
        "",
        f"The catalog holds **{len(models)} models** across **{len(families)} families**, "
        f"of which **{len(servable(models))}** are servable today. The paise columns are "
        "what you are billed, in full: there is nothing further added at invoice time. "
        "`GET /v1/manifold/models` reports the same figures live for the models your key "
        "can call.",
        "",
    ]
    (target.directory / f"catalog-summary{target.suffix}").write_text("\n".join(lines))


def write_vision(target, models: list[dict]) -> None:
    known = {model["alias"] for model in models}
    missing = VISION_ALIASES - known
    if missing:
        raise SystemExit(f"Vision aliases missing from the catalog: {sorted(missing)}")

    lines = [target.banner, ""]
    lines.extend(
        pending_admonition(
            target,
            [m["alias"] for m in models if m["alias"] in PENDING_ALIASES & VISION_ALIASES],
            "Pick one of the other aliases below for now.",
        )
    )
    lines.extend(
        [
            "| Alias | Model | Paise / 1K in | Paise / 1K out |",
            "|---|---|---:|---:|",
        ]
    )
    for model in models:
        if model["alias"] not in VISION_ALIASES:
            continue
        lines.append(
            "| `{alias}` | {name} | {pi} | {po} |".format(
                alias=model["alias"],
                name=model["displayName"],
                pi=paise(model["paisePer1KTokensIn"]),
                po=paise(model["paisePer1KTokensOut"]),
            )
        )
    lines.append("")
    (target.directory / f"model-vision{target.suffix}").write_text("\n".join(lines))


def write_budget(target, models: list[dict], count: int = 10) -> None:
    cheapest = sorted(
        servable(models),
        key=lambda m: (
            m["paisePer1KTokensIn"] + m["paisePer1KTokensOut"],
            m["alias"],
        ),
    )[:count]
    lines = [
        target.banner,
        "",
        "| Alias | Model | Paise / 1K in | Paise / 1K out | Paise for 1K in + 1K out |",
        "|---|---|---:|---:|---:|",
    ]
    for model in cheapest:
        total = model["paisePer1KTokensIn"] + model["paisePer1KTokensOut"]
        lines.append(
            "| `{alias}` | {name} | {pi} | {po} | {total} |".format(
                alias=model["alias"],
                name=model["displayName"],
                pi=paise(model["paisePer1KTokensIn"]),
                po=paise(model["paisePer1KTokensOut"]),
                total=paise(total),
            )
        )
    lines.append("")
    (target.directory / f"model-budget{target.suffix}").write_text("\n".join(lines))


# The billable dimensions of an embedding model, as (column heading, catalog field). Rendered
# only when some row actually prices that dimension, so a text-only lineup does not publish
# four empty columns and a reader is never shown a 0.00 that means "not applicable".
EMBEDDING_DIMENSIONS = (
    ("Paise / 1K tokens", "paisePer1KTokensIn"),
    ("Paise / image", "paisePerImage"),
    ("Paise / video sec", "paisePerVideoSecond"),
    ("Paise / audio sec", "paisePerAudioSecond"),
    ("Paise / request", "paisePerRequest"),
)


def write_embeddings(target, models: list[dict]) -> None:
    """The embeddings table, which cannot share the chat one.

    A chat row is priced in and out per 1K tokens. An embedding row has no output tokens and
    may be priced per image, per second of media, or per request instead, so the two need
    different columns rather than one table with blanks in it.
    """
    if not models:
        (target.directory / f"embedding-catalog{target.suffix}").write_text(
            "\n".join([target.banner, "", "No embedding models are servable today.", ""])
        )
        return

    used = [
        (heading, field)
        for heading, field in EMBEDDING_DIMENSIONS
        if any(model[field] != 0 for model in models)
    ]

    lines = [
        target.banner,
        "",
        "| Alias | Model | " + " | ".join(h for h, _ in used) + " |",
        "|---|---|" + "|".join("---:" for _ in used) + "|",
    ]
    lines += [
        "| `{alias}` | {name} | {cells} |".format(
            alias=model["alias"],
            name=model["displayName"],
            # A zero here means the model is not priced on that dimension at all, not that
            # it is free. "0.00" in a price column reads as free, so it is never printed:
            # a model that does not bill per image has no per-image price, which is a
            # different statement from one that bills nothing for it.
            cells=" | ".join(
                unit_paise(model[field]) if model[field] != 0 else "n/a"
                for _, field in used
            ),
        )
        for model in models
    ]
    lines.append("")
    (target.directory / f"embedding-catalog{target.suffix}").write_text("\n".join(lines))


def main() -> None:
    models = load()
    mdx_safe(models)

    # SPLIT BY KIND FIRST. Everything below this line that talks about "models" means chat
    # models: the family map, the vision column, the budget ranking and the per-1K-token
    # columns are all shaped for a surface that has an output price, and an embedding has no
    # output tokens at all. Ranking the two together sorted embeddings by a number that does
    # not exist for them, and the catalog table published a 0.00 output price beside a real
    # input one, which reads as free rather than as inapplicable.
    chat = [m for m in models if m.get("kind") != "embedding"]
    embeddings = [m for m in models if m.get("kind") == "embedding"]

    families = group(chat)
    for target in targets():
        target.directory.mkdir(exist_ok=True)
        write_catalog(target, families)
        write_summary(target, chat, families)
        write_vision(target, chat)
        write_budget(target, chat)
        write_embeddings(target, embeddings)
        print(f"wrote {target.directory.relative_to(ROOT)}/*{target.suffix}")
    print(f"{len(chat)} chat models, {len(families)} families, {len(embeddings)} embedding models")
    for family, entries in families.items():
        print(f"  {family}: {len(entries)}")


if __name__ == "__main__":
    main()
