#!/usr/bin/env python3
"""Generate the model and pricing tables from a captured GET /v1/manifold/models response.

Input:  data/models.json  (the response body, saved verbatim)
Output: includes/*.md     (markdown fragments pulled into the pages by pymdownx.snippets)

Every number on the model and pricing pages comes from here, so the published tables
cannot drift from the catalog they were captured from.

The weekly Catalog refresh workflow captures the catalog and runs this, opening a pull
request when anything moved. To do the same locally:

    TRISTACK_API_KEY=... python tools/fetch_catalog.py
    python tools/generate_pricing.py
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "models.json"
OUT = ROOT / "includes"

# How the catalog is grouped into families on the page, in the order the sections appear.
# Keyed on alias, never on the display name: the catalog names a model without any vendor
# prefix ("Nova Micro"), so a name carries nothing that can be relied on as a grouping key.
# Every alias in the catalog must appear here or the run fails.
FAMILIES: list[tuple[str, tuple[str, ...]]] = [
    ("Opus, Sonnet and Haiku", ("opus-5", "opus-4-8", "sonnet-5", "sonnet-4-6", "haiku-4-5")),
    ("Nova", ("nova-micro", "nova-lite", "nova-pro", "nova-2-lite")),
    ("DeepSeek", ("deepseek-v3-2", "deepseek-r1")),
    ("Gemma 3", ("gemma-3-4b", "gemma-3-12b", "gemma-3-27b")),
    ("Llama", ("llama-3-8b", "llama-3-70b", "llama-3-1-8b", "llama-3-1-70b", "llama-3-3-70b")),
    ("MiniMax", ("minimax-m2", "minimax-m2-1", "minimax-m2-5")),
    ("Devstral", ("devstral-2",)),
    ("Magistral", ("magistral-small",)),
    ("Mistral", ("mistral-7b", "mistral-large", "mistral-large-3", "mistral-small")),
    ("Pixtral", ("pixtral-large",)),
    ("Voxtral", ("voxtral-mini", "voxtral-small")),
    ("Ministral", ("ministral-3b", "ministral-8b", "ministral-14b")),
    ("Mixtral", ("mixtral-8x7b",)),
    ("Kimi", ("kimi-k2-thinking", "kimi-k2-5")),
    (
        "Nemotron",
        (
            "nemotron-nano-9b",
            "nemotron-nano-12b",
            "nemotron-nano-3-30b",
            "nemotron-super-120b",
        ),
    ),
    (
        "gpt-oss",
        ("gpt-oss-20b", "gpt-oss-120b", "gpt-oss-safeguard-20b", "gpt-oss-safeguard-120b"),
    ),
    (
        "Qwen3",
        ("qwen3-32b", "qwen3-coder-30b", "qwen3-coder-next", "qwen3-next-80b", "qwen3-vl-235b"),
    ),
    ("Palmyra", ("palmyra-vision-7b",)),
    ("GLM", ("glm-4-7", "glm-4-7-flash", "glm-5")),
]

# Aliases published in the catalog but not yet servable on this deployment. Calls to them
# answer 403 model_access_denied until the entitlement clears. Keyed on alias for the same
# reason the families are: availability is not something a display name can tell you.
PENDING_ALIASES = {
    "opus-5",
    "opus-4-8",
    "sonnet-5",
    "sonnet-4-6",
    "haiku-4-5",
}

# Aliases that accept image content blocks. The catalog endpoint does not report this, so
# it is tracked here and asserted against the catalog on every run. Delete this list in
# favour of the API the day the catalog response carries a vision flag of its own.
VISION_ALIASES = {
    "opus-5",
    "opus-4-8",
    "sonnet-5",
    "sonnet-4-6",
    "haiku-4-5",
    "nova-lite",
    "nova-pro",
    "nova-2-lite",
    "gemma-3-4b",
    "gemma-3-12b",
    "gemma-3-27b",
    "magistral-small",
    "ministral-3b",
    "ministral-8b",
    "ministral-14b",
    "mistral-large-3",
    "pixtral-large",
    "kimi-k2-5",
    "nemotron-nano-12b",
    "qwen3-vl-235b",
    "palmyra-vision-7b",
}

BANNER = "<!-- Generated by tools/generate_pricing.py from data/models.json. Do not edit. -->"


def lossless(value: Decimal, rendered: str) -> str:
    """
    Guard against publishing a rounded price. A rate the catalog carries at a precision the
    renderer cannot reproduce would ship as a wrong number rather than a failed build, which
    is the one failure mode a price table must not have.
    """
    if Decimal(rendered) != value:
        raise SystemExit(f"Rate {value} does not survive rendering as {rendered!r}")
    return rendered


def usd(value: Decimal) -> str:
    """USD per million tokens, at the precision the catalog actually carries."""
    two = value.quantize(Decimal("0.01"))
    # Two decimals where that is exact, otherwise every decimal the rate carries. `.3f`
    # here would silently round a 4-decimal rate, and 4-decimal per-MTok rates are ordinary.
    rendered = f"{two:.2f}" if two == value else format(value.normalize(), "f")
    return lossless(value, rendered)


def paise(value: Decimal) -> str:
    return lossless(value, f"{value:.2f}")


def servable(models: list[dict]) -> list[dict]:
    return [model for model in models if model["alias"] not in PENDING_ALIASES]


def load() -> tuple[Decimal, list[dict]]:
    payload = json.loads(SOURCE.read_text(), parse_float=Decimal, parse_int=Decimal)
    return payload["usdToInr"], payload["models"]


def group(models: list[dict]) -> dict[str, list[dict]]:
    """
    Split the catalog into the families above, failing loudly rather than guessing: an
    alias nobody mapped would otherwise vanish from the page, and a pending alias that
    left the catalog would leave a warning standing over nothing.
    """
    mapped = [alias for _, aliases in FAMILIES for alias in aliases]
    duplicated = sorted({alias for alias in mapped if mapped.count(alias) > 1})
    if duplicated:
        raise SystemExit(f"Aliases listed in more than one family: {duplicated}")

    known = {model["alias"] for model in models}
    unmapped = sorted(known - set(mapped))
    if unmapped:
        raise SystemExit(f"Catalog aliases with no family in FAMILIES: {unmapped}")

    stale = sorted((set(mapped) | PENDING_ALIASES) - known)
    if stale:
        raise SystemExit(f"Aliases mapped here but missing from the catalog: {stale}")

    by_alias = {model["alias"]: model for model in models}
    return {
        heading: [by_alias[alias] for alias in aliases] for heading, aliases in FAMILIES
    }


def catalog_rows(models: list[dict]) -> list[str]:
    header = [
        "| Alias | Model | Vision | USD / MTok in | USD / MTok out | Paise / 1K in | Paise / 1K out |",
        "|---|---|:--:|---:|---:|---:|---:|",
    ]
    rows = [
        "| `{alias}` | {name} | {vision} | {ui} | {uo} | {pi} | {po} |".format(
            alias=model["alias"],
            name=model["displayName"],
            vision="yes" if model["alias"] in VISION_ALIASES else "",
            ui=usd(model["usdPerMTokIn"]),
            uo=usd(model["usdPerMTokOut"]),
            pi=paise(model["paisePer1KTokensIn"]),
            po=paise(model["paisePer1KTokensOut"]),
        )
        for model in models
    ]
    return header + rows


def pending_admonition(aliases: list[str], closing: str) -> list[str]:
    """
    The "not servable yet" warning, emitted above the rows it covers so a reader scanning
    the table meets it before the prices. Generated from PENDING_ALIASES everywhere it
    appears: a hand-typed copy would outlive the entitlement it describes.

    The cause is deliberately left at "account-level access": nothing in the catalog
    response reports why an alias is unservable, so anything more specific would be invented.
    """
    if not aliases:
        return []
    named = ", ".join(f"`{alias}`" for alias in aliases)
    return [
        '!!! warning "Not servable yet"',
        "",
        f"    {named} are published in the catalog but are not servable yet while "
        "account-level access is being finalised, so a call answers "
        f"`403 model_access_denied`. {closing}",
        "",
    ]


def write_catalog(families: dict[str, list[dict]]) -> None:
    lines = [BANNER, ""]
    for family, models in families.items():
        lines.append(f"### {family}")
        lines.append("")
        lines.extend(
            pending_admonition(
                [m["alias"] for m in models if m["alias"] in PENDING_ALIASES],
                "The prices below are what they will bill once that clears.",
            )
        )
        lines.extend(catalog_rows(models))
        lines.append("")
    (OUT / "model-catalog.md").write_text("\n".join(lines))


def write_summary(fx: Decimal, models: list[dict], families: dict[str, list[dict]]) -> None:
    lines = [
        BANNER,
        "",
        f"The catalog holds **{len(models)} models** across **{len(families)} families**, "
        f"of which **{len(servable(models))}** are servable today. Prices are converted at "
        f"**{fx:.1f} INR per USD**, the `usdToInr` value the catalog endpoint returned "
        "when this table was captured.",
        "",
    ]
    (OUT / "catalog-summary.md").write_text("\n".join(lines))


def write_vision(models: list[dict]) -> None:
    known = {model["alias"] for model in models}
    missing = VISION_ALIASES - known
    if missing:
        raise SystemExit(f"Vision aliases missing from the catalog: {sorted(missing)}")

    lines = [BANNER, ""]
    lines.extend(
        pending_admonition(
            [m["alias"] for m in models if m["alias"] in PENDING_ALIASES & VISION_ALIASES],
            "Pick one of the other aliases below for now.",
        )
    )
    lines.extend(
        [
            "| Alias | Model | Paise / 1K in | Paise / 1K out |",
            "|---|---|---:|---:|",
        ]
    )
    for model in models:
        if model["alias"] not in VISION_ALIASES:
            continue
        lines.append(
            "| `{alias}` | {name} | {pi} | {po} |".format(
                alias=model["alias"],
                name=model["displayName"],
                pi=paise(model["paisePer1KTokensIn"]),
                po=paise(model["paisePer1KTokensOut"]),
            )
        )
    lines.append("")
    (OUT / "model-vision.md").write_text("\n".join(lines))


def write_budget(models: list[dict], count: int = 10) -> None:
    cheapest = sorted(
        servable(models),
        key=lambda m: (
            m["paisePer1KTokensIn"] + m["paisePer1KTokensOut"],
            m["alias"],
        ),
    )[:count]
    lines = [
        BANNER,
        "",
        "| Alias | Model | Paise / 1K in | Paise / 1K out | Paise for 1K in + 1K out |",
        "|---|---|---:|---:|---:|",
    ]
    for model in cheapest:
        total = model["paisePer1KTokensIn"] + model["paisePer1KTokensOut"]
        lines.append(
            "| `{alias}` | {name} | {pi} | {po} | {total} |".format(
                alias=model["alias"],
                name=model["displayName"],
                pi=paise(model["paisePer1KTokensIn"]),
                po=paise(model["paisePer1KTokensOut"]),
                total=paise(total),
            )
        )
    lines.append("")
    (OUT / "model-budget.md").write_text("\n".join(lines))


def main() -> None:
    fx, models = load()
    families = group(models)
    OUT.mkdir(exist_ok=True)
    write_catalog(families)
    write_summary(fx, models, families)
    write_vision(models)
    write_budget(models)
    print(f"{len(models)} models, {len(families)} families, fx {fx}")
    for family, entries in families.items():
        print(f"  {family}: {len(entries)}")


if __name__ == "__main__":
    main()
